export enum ModuleType {
  OBRAS_INVESTIMENTO = 'OBRAS_INVESTIMENTO',
  OBRAS_GLOBAL = 'OBRAS_GLOBAL',
  CANTEIRO = 'CANTEIRO',
  QUALIDADE = 'QUALIDADE',
  CAMPO = 'CAMPO',
  SEGURANCA_TRABALHO = 'SEGURANCA_TRABALHO',
  REMOTO = 'REMOTO',
  POS_OBRA = 'POS_OBRA',
}
