export enum ModuleType {
  QUALIDADE = 'QUALIDADE',
  SEGURANCA_TRABALHO = 'SEGURANCA_TRABALHO',
  OBRAS_INVESTIMENTO = 'OBRAS_INVESTIMENTO',
  OBRAS_GLOBAL = 'OBRAS_GLOBAL',
  CANTEIRO = 'CANTEIRO',
}
